### ISSUE TITLE
Installation fails because of ffmpeg0.10

### ISSUE THREAD

**Issue by nutax** [variadico/xpslinux#14]
It looks like there's something wrong with the ffmpeg0.10. It will in turn crash the whole installation process.

**Comment by bbozhev** [comment]
@nutax it installs version specific ffmpeg in this case 0.10 meaning it's not available anymore or the package itself is missing for some reason, you can build the binary file yourself just clone the repo and modify phasetwo.go you will find the ffmpeg package on line 197: 

`
	pkgs := []string{
		"systemd-swap",
		"intel-ucode",
                ......................
		"ffmpeg0.10",
`

Just replace ffmpeg0.10 with ffmpeg and run go build inside of the repository directory which should generate the binary file with the ffmpeg package installation script instead of ffmpeg0.10 and fix your issue.

Worked perfectly for me ! 

Thanks for the wonderful tool @variadico

**Comment by variadico** [comment]
Sorry for the late reply. Both of you guys are awesome! I just put up a PR for the change.
https://github.com/variadico/xpslinux/pull/15

I can build a new release soon too. Thanks!
